openapi: 3.0.0
info:
  title: Health App API
  description: This API receives reading events from diabetic medical devices
  contact:
    email: jlodhra@bcit.ca
  version: 1.0.0
tags:
- name: readings
  description: Operations available to diabetic medical device readings
paths:
  /readings/personal_information:
    post:
      summary: reports a blood sugar reading
      description: "Adds a new blood sugar reading to the system"
      operationId: app.personal_information
      responses:
        "201": 
          description: item created i.e. success
        "400":
          description: invalid input, object invalid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonalInformationEntry'

  /readings/start_end_date:
    post:
      summary: reports a cortisol reading
      description: "Adds a new cortisol reading to the system"
      operationId: app.start_end_date
      responses:
        "201": 
          description: item created i.e. success
        "400":
          description: invalid input, object invalid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MembershipValidity'

components:
  schemas:
    PersonalInformationEntry:
      required:
        - member_id
        - name
        - address
        - age
      type: object
      properties:
        member_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: 'Annson Ramos'
        age:
          type: integer
          example: 20
        address:
          type: string
          example: '123 Cambie St, Vancouver'
    MembershipValidity:
      required:
        - member_id
        - location_id
        - start_date
        - duration_months
      type: object
      properties:
        member_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        location_id:
          type: string
          example: CL9012
        duration_months:
          type: integer
          example: 40
        start_date:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
